# Generated by Django 3.0.8 on 2020-07-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Basliq')),
                ('company_name', models.CharField(max_length=100, verbose_name='Müəsisə adı')),
                ('company_email', models.CharField(max_length=50, verbose_name='email')),
                ('job_type', models.CharField(max_length=50, verbose_name='işin tipi')),
                ('salary', models.CharField(max_length=50, verbose_name='maaş')),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
    ]
