# Generated by Django 3.0.8 on 2020-07-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0002_elan'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elan.Categories'),
        ),
    ]
