# Generated by Django 3.0.8 on 2020-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0003_elan_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='elan',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='elan',
            name='experience',
            field=models.CharField(max_length=50, verbose_name='Iş təcrübəsi'),
        ),
        migrations.AlterField(
            model_name='elan',
            name='job_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='işin tipi'),
        ),
        migrations.AlterField(
            model_name='elan',
            name='salary',
            field=models.CharField(blank=True, max_length=50, verbose_name='maaş'),
        ),
    ]
