# Generated by Django 3.0.8 on 2020-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0004_auto_20200724_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='job_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
