# Generated by Django 3.0.8 on 2020-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0005_elan_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='image_field',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
