# Generated by Django 3.0.8 on 2020-07-24 14:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0007_auto_20200724_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='job_requirements',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
