# Generated by Django 3.0.8 on 2020-07-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elan', '0008_elan_job_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elan',
            options={'ordering': ('-start_date',)},
        ),
    ]
